language: php

php:
- 7.1
- 7.2
- 7.3

services:
- mysql
- postgresql

env:
- DB_CONNECTION=sqlite DB_DATABASE=./database.sqlite
- DB_CONNECTION=pgsql DB_HOST=localhost DB_DATABASE=test DB_USERNAME=postgres DB_PASSWORD=
- DB_CONNECTION=mysql DB_HOST=localhost DB_DATABASE=test DB_USERNAME=root DB_PASSWORD=

before_install:
- mysql -e "CREATE DATABASE $DB_DATABASE;"
- psql -c "create database $DB_DATABASE;" -U postgres

before_script:
- composer install --no-suggest --no-progress --no-interaction
- touch ./database.sqlite
- composer dump-autoload -o
- php -v
- composer -V
- echo $DB_CONNECTION
- composer show 'laravel/framework' | grep 'versions' | grep -o -E '\*\ .+' | cut -d' ' -f2 | cut -d',' -f1;
- composer show 'orchestra/testbench' | grep 'versions' | grep -o -E '\*\ .+' | cut -d' ' -f2 | cut -d',' -f1;

