language: php

services:
- mysql
- postgresql

branches:
  only:
  - master

cache:
  directories:
  - $HOME/.composer/cache

env:
  global:
  - DB_HOST=localhost
  - DB_DATABASE=test
  - DB_PASSWORD=

matrix:
  fast_finish: true
  include:
  - php: 7.1
    env: LARAVEL='5.5.*' TESTBENCH='3.5.*' DB_CONNECTION=mysql DB_USERNAME=root
  - php: 7.1
    env: LARAVEL='5.6.*' TESTBENCH='3.6.*' DB_CONNECTION=mysql DB_USERNAME=root
  - php: 7.1
    env: LARAVEL='5.7.*' TESTBENCH='3.7.*' DB_CONNECTION=mysql DB_USERNAME=root
  - php: 7.1
    env: LARAVEL='5.5.*' TESTBENCH='3.5.*' DB_CONNECTION=pgsql DB_USERNAME=postgres
  - php: 7.1
    env: LARAVEL='5.6.*' TESTBENCH='3.6.*' DB_CONNECTION=pgsql DB_USERNAME=postgres
  - php: 7.1
    env: LARAVEL='5.7.*' TESTBENCH='3.7.*' DB_CONNECTION=pgsql DB_USERNAME=postgres
  - php: 7.1
    env: LARAVEL='5.5.*' TESTBENCH='3.5.*' DB_CONNECTION=sqlite DB_DATABASE=./database.sqlite
  - php: 7.1
    env: LARAVEL='5.6.*' TESTBENCH='3.6.*' DB_CONNECTION=pgsql DB_USERNAME=postgres
  - php: 7.1
    env: LARAVEL='5.7.*' TESTBENCH='3.7.*' DB_CONNECTION=pgsql DB_USERNAME=postgres
  - php: 7.2
    env: LARAVEL='5.5.*' TESTBENCH='3.5.*' DB_CONNECTION=mysql DB_USERNAME=root
  - php: 7.2
    env: LARAVEL='5.6.*' TESTBENCH='3.6.*' DB_CONNECTION=mysql DB_USERNAME=root
  - php: 7.2
    env: LARAVEL='5.7.*' TESTBENCH='3.7.*' DB_CONNECTION=mysql DB_USERNAME=root
  - php: 7.2
    env: LARAVEL='5.5.*' TESTBENCH='3.5.*' DB_CONNECTION=pgsql DB_USERNAME=postgres
  - php: 7.2
    env: LARAVEL='5.6.*' TESTBENCH='3.6.*' DB_CONNECTION=pgsql DB_USERNAME=postgres
  - php: 7.2
    env: LARAVEL='5.7.*' TESTBENCH='3.7.*' DB_CONNECTION=pgsql DB_USERNAME=postgres
  - php: 7.2
    env: LARAVEL='5.5.*' TESTBENCH='3.5.*' DB_CONNECTION=sqlite DB_DATABASE=./database.sqlite
  - php: 7.2
    env: LARAVEL='5.6.*' TESTBENCH='3.6.*' DB_CONNECTION=sqlite DB_DATABASE=./database.sqlite
  - php: 7.2
    env: LARAVEL='5.7.*' TESTBENCH='3.7.*' DB_CONNECTION=sqlite DB_DATABASE=./database.sqlite
  - php: 7.3
    env: LARAVEL='5.5.*' TESTBENCH='3.5.*' DB_CONNECTION=mysql DB_USERNAME=root
  - php: 7.3
    env: LARAVEL='5.6.*' TESTBENCH='3.6.*' DB_CONNECTION=mysql DB_USERNAME=root
  - php: 7.3
    env: LARAVEL='5.7.*' TESTBENCH='3.7.*' DB_CONNECTION=mysql DB_USERNAME=root
  - php: 7.3
    env: LARAVEL='5.5.*' TESTBENCH='3.5.*' DB_CONNECTION=pgsql DB_USERNAME=postgres
  - php: 7.3
    env: LARAVEL='5.6.*' TESTBENCH='3.6.*' DB_CONNECTION=pgsql DB_USERNAME=postgres
  - php: 7.3
    env: LARAVEL='5.7.*' TESTBENCH='3.7.*' DB_CONNECTION=pgsql DB_USERNAME=postgres
  - php: 7.3
    env: LARAVEL='5.5.*' TESTBENCH='3.5.*' DB_CONNECTION=sqlite DB_DATABASE=./database.sqlite
  - php: 7.3
    env: LARAVEL='5.6.*' TESTBENCH='3.6.*' DB_CONNECTION=sqlite DB_DATABASE=./database.sqlite
  - php: 7.3
    env: LARAVEL='5.7.*' TESTBENCH='3.7.*' DB_CONNECTION=sqlite DB_DATABASE=./database.sqlite

before_install:
- |
  if [ "$DB_CONNECTION" == 'mysql' ]; then
    mysql -e "CREATE DATABASE $DB_DATABASE;";
  elif [ "$DB_CONNECTION" == 'pgsql' ]; then
    psql -c "create database $DB_DATABASE;" -U postgres;
  elif [ "$DB_CONNECTION" == 'sqlite' ]; then
    touch ./database.sqlite;
  else
    echo "invalid DB_CONNECTION: $DB_CONNECTION"
  fi
- travis_retry composer self-update
- travis_retry composer require --no-update --no-interaction "illuminate/support:${LARAVEL}" "orchestra/testbench:${TESTBENCH}" "orchestra/database:${TESTBENCH}"

install:
- travis_retry composer update --no-interaction --no-plugins --no-suggest
- travis_retry composer dump-autoload -o

script:
- composer ci-test

after_success:
- php vendor/bin/php-coveralls -v
