language: php

php:
- 7.1
- 7.2
- 7.3

services:
- mysql
- postgresql

env:
- DB_CONNECTION=mysql DB_HOST=localhost DB_DATABASE=test DB_USERNAME=root DB_PASSWORD=
- DB_CONNECTION=pgsql DB_HOST=localhost DB_DATABASE=test DB_USERNAME=postgres DB_PASSWORD=
- DB_CONNECTION=sqlite DB_DATABASE=./database.sqlite

before_install:
- |
  if [ $DB_CONNECTION = 'mysql' ]; then
    mysql -e "CREATE DATABASE $DB_DATABASE;";
  elif [ $DB_CONNECTION = 'pgsql' ]; then
    psql -c "create database $DB_DATABASE;" -U postgres;
  elif [ $DB_CONNECTION = 'sqlite' ]; then
    touch ./database.sqlite;
  else
    echo "invalid DB_CONNECTION: $DB_CONNECTION"
  fi

install:
- composer install --no-suggest --no-progress --no-interaction
- composer dump-autoload -o

before_script:
- php -v
- composer -V
- echo $DB_CONNECTION
- composer show 'laravel/framework' | grep 'versions' | grep -o -E '\*\ .+' | cut -d' ' -f2 | cut -d',' -f1;
- composer show 'orchestra/testbench' | grep 'versions' | grep -o -E '\*\ .+' | cut -d' ' -f2 | cut -d',' -f1;

